import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.TEST_URL||'http://localhost:5178');
await page.locator('#canvas').waitFor();
await page.locator('#pause').click();
const pixels=()=>page.locator('#canvas').evaluate(c=>c.toDataURL());
const original=await pixels();
await page.locator('#intensity').fill('0.3');assert.notEqual(await pixels(),original);
await page.getByRole('button',{name:'Empty',exact:true}).click();assert.equal(await page.locator('#frame').isChecked(),false);assert.equal(await page.locator('#glass').isChecked(),false);assert.equal(await page.locator('#enabled').isChecked(),false);
await page.getByRole('button',{name:'Ice',exact:true}).click();assert.equal(await page.locator('#enabled').isChecked(),true);
await page.locator('[data-port="dispersion"]').click();assert.equal(await page.locator('[data-node="dispersion"]').getAttribute('class'),'node bypassed');
await page.locator('[data-port="dispersion"]').click();assert.equal(await page.locator('[data-port="dispersion"]').getAttribute('aria-pressed'),'true');
const handle=page.locator('[data-node="source"] .node-heading');await handle.focus();const left=await handle.evaluate(el=>el.parentElement.offsetLeft);await page.keyboard.press('ArrowRight');assert.equal(await handle.evaluate(el=>el.parentElement.offsetLeft),left+10);
const box=await handle.boundingBox();await page.mouse.move(box.x+60,box.y+15);await page.mouse.down();await page.mouse.move(box.x+95,box.y+30);await page.mouse.up();assert.equal(await handle.evaluate(el=>el.parentElement.offsetLeft),left+45);
await page.locator('#arrange').click();assert.equal(await handle.evaluate(el=>el.parentElement.offsetLeft),30);
await page.locator('#present').click();assert.equal(await page.locator('.inspector').isVisible(),false);await page.keyboard.press('Escape');assert.equal(await page.locator('.inspector').isVisible(),true);
const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'light-chamber.png');await download.saveAs('artifacts/export.png');
await page.locator('#reset').click();await page.screenshot({path:'artifacts/desktop.png'});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#toggle-inspector').click();await page.locator('#toggle-graph').click();await page.screenshot({path:'artifacts/mobile-canvas.png'});
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: shader pixels, presets, connections, pointer/keyboard dragging, presentation, PNG export, mobile, no runtime errors');
