import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
await page.goto(process.env.TEST_URL || 'http://localhost:5178');
await page.locator('#canvas').waitFor();
const pixels=async()=>createHash('sha256').update(await page.locator('#canvas').evaluate(canvas=>canvas.toDataURL())).digest('hex');
await page.waitForTimeout(200);
assert.equal(await page.locator('body').innerText(),'');
assert.equal(await page.locator('button,input,aside,nav,.graph,.panel').count(),0);
const original=await pixels();
await page.mouse.move(1100,280);
await page.waitForTimeout(1400);
const moved=await pixels();
assert.notEqual(moved,original,'cursor must alter rendered geometry');
await page.mouse.wheel(0,400);
await page.waitForTimeout(1400);
assert.notEqual(await pixels(),moved,'scroll must change spatial depth');
await page.emulateMedia({reducedMotion:'reduce'});
await page.locator('#canvas').focus();
await page.keyboard.press('Escape');
await page.waitForTimeout(1400);
assert.equal(await pixels(),original,'reset restores identical deterministic scene');
await page.keyboard.press('ArrowLeft');
await page.waitForTimeout(1400);
assert.notEqual(await pixels(),original,'keyboard must steer scene');
await page.keyboard.press('Escape');
await page.waitForTimeout(1400);
await page.screenshot({path:'artifacts/desktop.png'});
await page.mouse.move(1080,320);await page.waitForTimeout(1400);
await page.screenshot({path:'artifacts/spatial.png'});
await page.setViewportSize({width:390,height:844});
await page.keyboard.press('Escape');await page.waitForTimeout(1400);
await page.screenshot({path:'artifacts/mobile.png'});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.emulateMedia({reducedMotion:'reduce'});
await page.keyboard.press('ArrowRight');await page.waitForTimeout(100);
const still=await pixels();await page.waitForTimeout(200);
assert.equal(await pixels(),still,'dither must stay still without temporal noise');
const fallback=await browser.newPage();
await fallback.addInitScript(()=>{HTMLCanvasElement.prototype.getContext=()=>null;});
await fallback.goto(process.env.TEST_URL || 'http://localhost:5178');
assert.match(await fallback.locator('[role=alert]').textContent(),/WebGL/);
assert.deepEqual(errors,[]);
await browser.close();
console.log('PASS: UI removed, pointer orbit, depth, keyboard, deterministic reset/dither, mobile, reduced motion, WebGL fallback');
