import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
await page.goto(process.env.TEST_URL || 'http://localhost:5178');
await page.locator('#canvas').waitFor();
const pixels=async()=>createHash('sha256').update(await page.locator('#canvas').evaluate(canvas=>canvas.toDataURL())).digest('hex');
await page.waitForTimeout(200);
assert.equal(await page.locator('body').innerText(),'');
assert.equal(await page.locator('button,input,aside,nav,.graph,.panel').count(),0);
const original=await pixels();
await page.mouse.move(1100,280);
await page.waitForTimeout(1400);
const moved=await pixels();
assert.notEqual(moved,original,'cursor must alter lighting and refraction');
await page.mouse.wheel(0,400);
await page.waitForTimeout(1400);
assert.notEqual(await pixels(),moved,'scroll must change light depth');
await page.emulateMedia({reducedMotion:'reduce'});
await page.locator('#canvas').focus();
await page.keyboard.press('Escape');
await page.waitForTimeout(1400);
assert.equal(await pixels(),original,'reset restores identical deterministic scene');
await page.keyboard.press('ArrowLeft');
await page.waitForTimeout(1400);
assert.notEqual(await pixels(),original,'keyboard must move the light');
await page.keyboard.press('Escape');
await page.waitForTimeout(1400);
await page.screenshot({path:'artifacts/desktop.png'});
await page.mouse.move(1080,320);await page.waitForTimeout(1400);
await page.screenshot({path:'artifacts/spatial.png'});
await page.setViewportSize({width:390,height:844});
await page.keyboard.press('Escape');await page.waitForTimeout(1400);
await page.screenshot({path:'artifacts/mobile.png'});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.emulateMedia({reducedMotion:'reduce'});
await page.keyboard.press('ArrowRight');await page.waitForTimeout(100);
const still=await pixels();await page.waitForTimeout(200);
assert.equal(await pixels(),still,'dither must stay still without temporal noise');
const beforeRestore=await pixels();
await page.evaluate(()=>new Promise((resolve,reject)=>{
  const canvas=document.querySelector('#canvas');
  const extension=canvas.getContext('webgl').getExtension('WEBGL_lose_context');
  if(!extension){reject(new Error('Context-loss extension unavailable'));return;}
  canvas.addEventListener('webglcontextrestored',()=>requestAnimationFrame(()=>requestAnimationFrame(resolve)),{once:true});
  canvas.addEventListener('webglcontextlost',()=>setTimeout(()=>extension.restoreContext(),150),{once:true});
  extension.loseContext();
}));
assert.equal(await pixels(),beforeRestore,'restored GPU context renders same scene');
const animated=await browser.newPage({viewport:{width:720,height:600},reducedMotion:'no-preference'});
await animated.goto(process.env.TEST_URL || 'http://localhost:5178');
await animated.waitForTimeout(200);
const filmBefore=await animated.locator('#canvas').evaluate(c=>c.toDataURL());
await animated.waitForTimeout(700);
const filmAfter=await animated.locator('#canvas').evaluate(c=>c.toDataURL());
assert.ok(filmBefore!==filmAfter,'wind must animate without moving the pointer');
await animated.locator('#canvas').focus();
await animated.keyboard.press('Space');await animated.waitForTimeout(150);
const paused=await animated.locator('#canvas').evaluate(c=>c.toDataURL());
await animated.waitForTimeout(300);
assert.ok(paused===await animated.locator('#canvas').evaluate(c=>c.toDataURL()),'Space freezes wind');
await animated.keyboard.press('Space');await animated.waitForTimeout(300);
assert.ok(paused!==await animated.locator('#canvas').evaluate(c=>c.toDataURL()),'Space resumes wind');
await animated.close();
const touch=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true,reducedMotion:'reduce'});
await touch.goto(process.env.TEST_URL || 'http://localhost:5178');
const touchBefore=await touch.locator('#canvas').evaluate(c=>c.toDataURL());
await touch.touchscreen.tap(290,350);await touch.waitForTimeout(150);
assert.ok(touchBefore!==await touch.locator('#canvas').evaluate(c=>c.toDataURL()),'touch positions light');
await touch.close();
const fallback=await browser.newPage();
await fallback.addInitScript(()=>{HTMLCanvasElement.prototype.getContext=()=>null;});
await fallback.goto(process.env.TEST_URL || 'http://localhost:5178');
assert.match(await fallback.locator('[role=alert]').textContent(),/WebGL/);
assert.deepEqual(errors,[]);
await browser.close();
console.log('PASS: text-free canvas, pointer light, source depth, keyboard, deterministic reset/dither, wind animation, touch, mobile, reduced motion, WebGL fallback');
